[package]
name = "par_download"
version = "0.1.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"
description = "Fast and simple async downloads"
readme = "README.md"
repository = "https://github.com/x0f5c3/par_download"
license = "MIT"
keywords = ["download", "http", "async"]
categories = ["asynchronous","web-programming::http-client", "network-programming"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
progress = ["indicatif"]

[dependencies]
tokio = { version = "^0.2.5", features = ["fs", "rt-threaded", "macros"] }
thiserror = "*"
url = "*"
sha2 = "*"
indicatif = { version = "*", optional = true }
tracing = { version = "*", features = ["log"] }
tracing-futures = "*"
smallvec = "*"


[dependencies.reqwest]
version = "0.10.9"
default-features = false
features = ["rustls-tls"]


