[package]
name = "manic"
version = "0.2.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"
description = "Fast and simple async downloads"
readme = "README.md"
repository = "https://github.com/x0f5c3/manic"
license = "MIT OR Apache-2.0"
keywords = ["download", "http", "async"]
categories = ["asynchronous","web-programming::http-client", "network-programming"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
progress = ["indicatif"]

[dependencies]
tokio = { version = "^0.2.5", features = ["fs", "rt-threaded", "macros"] }
thiserror = "1.0.22"
url = "2.2.0"
sha2 = "0.9.2"
indicatif = { version = "0.15.0", optional = true }
tracing = { version = "0.1.22", features = ["log"] }
tracing-futures = "0.2.4"


[dependencies.reqwest]
version = "0.10.9"
default-features = false
features = ["rustls-tls"]


